### ISSUE TITLE
Member Types at Registration

### ISSUE THREAD

**Issue by romanzy** [imath/bp-mt-extended#1]
Dear Mathieu,

I'm willing to add a required Member Types selection at BuddyPress Registration via Base XProfile Fields. 

If I'm not wrong, I saw somewhere an article from you about this issue, but I cannot find it anymore. Do you have a code snippet for it? Did it work with bp-mt-extended?

Thank you if you could help me out with this.

Regards

**Comment by imath** [comment]
Hi, 

If i had to do this, i think i would simply hook to one of the register.php template hooks to output the selectbox and then find the hook to include the selected value into the signups meta to finally set the member type for the user once the account is activated by hooking again to the right hook to get the signup's meta i've previously included.

imath.
http://profiles.wordpress.org/imath/
